name: pull-request

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run eslint
        run: npm run lint:js:fix
      - name: Run tests 
        run: npm run test