name: pull-request

on:
  pull_request:
    branches: [ master ]
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run ESLint
      - uses: stefanoeb/eslint-action@1.0.2
      - name: lint files
        run: npm run lint:js:fix
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run Jest
      - uses: stefanoeb/jest-action@1.0.3
      - name: run unit tests 
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "erica-cicd-testing"
          heroku_email: "evoingram@aquoco.onmicrosoft.com"

        